# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(max_length=100)),
                ('question_name', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('submitted_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('logged_in_time', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RITCSE_codeWars.Users'),
        ),
    ]
