# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RITCSE_codeWars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
