# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RITCSE_codeWars', '0002_submission_submission_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_start_date',
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_end_date',
            field=models.DateTimeField(),
        ),
    ]
