# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RITCSE_codeWars', '0004_submission_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
