# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RITCSE_codeWars', '0005_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 10, 8, 26, 12, 348183, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
