# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RITCSE_codeWars', '0006_contest_contest_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
